# Generated by Django 5.2.6 on 2025-11-04 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0003_job_jobprogram_job_eligible_programs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydrive',
            old_name='drive',
            new_name='placement_drive',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='drive',
            new_name='company_drive',
        ),
        migrations.AlterUniqueTogether(
            name='companydrive',
            unique_together=set(),
        ),
    ]
