# Generated by Django 5.2.6 on 2025-11-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0004_changed_name_of_placement_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydrive',
            name='multiple_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
