# Generated by Django 5.2.6 on 2025-11-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0005_added_field_in_companydrive'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_desc',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
