# Generated by Django 5.2.6 on 2025-10-12 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='degree',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name']},
        ),
    ]
