# Generated by Django 5.2.6 on 2025-10-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_company_logo_url_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_size',
            field=models.IntegerField(blank=True, choices=[(0, 'Self'), (1, '1–10 employees'), (2, '11–50 employees'), (3, '51–500 employees'), (4, '500+ employees')], null=True),
        ),
    ]
