# Generated by Django 5.2.6 on 2025-10-11 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_modified_company_size_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default=datetime.datetime(2025, 10, 11, 17, 12, 37, 698233), max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone_number',
            field=models.CharField(default=datetime.datetime(2025, 10, 11, 17, 12, 45, 801882), max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
