# Generated by Django 5.2.6 on 2025-11-04 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_unlink_user_table_from_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Companies'},
        ),
    ]
