# Generated by Django 5.2.6 on 2025-10-26 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_jobapplication_resume_url_and_more'),
        ('placements', '0003_job_jobprogram_job_eligible_programs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='placements.job'),
        ),
    ]
