# Generated by Django 5.2.6 on 2025-11-08 05:58

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_jobapplication_job'),
        ('placements', '0004_changed_name_of_placement_tables'),
        ('students', '0004_is_verified_field_in_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDriveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Reviewed', 'Reviewed'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Offered', 'Offered'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Applied', max_length=20)),
                ('resume', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='placements.companydrive')),
                ('offered_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offered_applications', to='placements.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('company_drive', 'student')},
            },
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
