# Generated by Django 5.2.6 on 2025-11-08 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_changed_jobapplication_to_companyapplication'),
        ('placements', '0005_added_field_in_companydrive'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_order', models.PositiveIntegerField(default=1)),
                ('drive_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_preferences', to='applications.companydriveapplication')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placements.job')),
            ],
            options={
                'ordering': ['preference_order'],
                'unique_together': {('drive_application', 'job'), ('drive_application', 'preference_order')},
            },
        ),
    ]
