# Generated by Django 5.2.6 on 2025-11-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_added_job_preference_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydriveapplication',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Withdrawn', 'Withdrawn'), ('Offered', 'Offered'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Applied', max_length=20),
        ),
    ]
