# Generated by Django 5.2.6 on 2025-11-09 08:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_status_choices_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydriveapplication',
            name='resume',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
