# Generated by Django 5.2.6 on 2025-11-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_changed_resume_to_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydriveapplication',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Offered', 'Offered'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Applied', max_length=20),
        ),
    ]
