# Generated by Django 5.2.6 on 2025-11-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_studentprofile_profile_picture_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='joining_year',
            field=models.IntegerField(default=2024),
        ),
    ]
