# Generated by Django 5.2.6 on 2025-11-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_added_joining_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
