# Generated by Django 5.2.6 on 2025-11-09 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_city_options_alter_country_options_and_more'),
        ('students', '0004_is_verified_field_in_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_verified', True), _negated=True), models.Q(('tenth_percentage__isnull', False), ('twelfth_percentage__isnull', False), ('current_cgpa__isnull', False)), _connector='OR'), name='verified_student_has_required_data'),
        ),
    ]
